Fixed env references

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,7 +8,7 @@ inputs:
   ref:
     description: 'Specify a branch, tag or SHA. This defaults to the reference or SHA for the workflow event.'
     required: false
-    default: ${{ github.ref || github.sha}}
+    default: ${{ github.head_ref || github.ref_name || github.sha }}
   timeout:
     description: 'The time allowance in seconds for waiting the checks to pass.'
     required: false
@@ -20,15 +20,11 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - uses: actions/checkout@v4
-      with:
-        ref: ${{ inputs.ref }}
-
     - name: Get current workflow run
       id: get-current-workflow-run
       shell: bash
       env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GH_TOKEN: ${{ inputs.github-token }}
         REPO: ${{ github.repository }}
         RUN_ID: ${{ github.run_id }}
       run: |
@@ -60,9 +56,11 @@ runs:
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "/repos/$REPO/actions/runs/$RUN_ID/jobs" \
-          --jq '[.jobs[].id]')
-        JOB_ID_LIST=$(echo $JOB_IDS | tr '\n' ',' | sed -E 's/,/, /g; s/, $/\n/g')
+          --jq '[.jobs[].id]' |
+          jq -c '.')
+        JOB_ID_LIST=$(echo $JOB_IDS | jq -r '.[]' | tr '\n' ',' | sed -E 's/,/, /g; s/, $/\n/g')
         echo "::notice::Ids of all jobs in the workflow run are $JOB_ID_LIST"
+        echo "$JOB_IDS" | jq '.'
 
         echo "job-ids=$JOB_IDS" >> $GITHUB_OUTPUT
 
@@ -70,68 +68,144 @@ runs:
       id: get-git-ref-metadata
       shell: bash
       env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GH_TOKEN: ${{ inputs.github-token }}
         REF: ${{ inputs.ref }}
       run: |
         echo "::notice::Git reference is $REF"
 
-        REF_NAME=$(git name-rev --name-only "$REF")
-        if [[ "$REF" != "$REF_NAME" ]]; then
-          echo "::notice::$REF is $REF_NAME"
-        if
+        if (git cat-file -t "$REF")
+        then
+          SHA=$(git rev-parse --short "$REF")
 
-        REF_FULL_NAME=$(git rev-parse --symbolic-full-name "$REF_NAME")
-        echo "ref-full-name=$REF_FULL_NAME" >> $GITHUB_OUTPUT
-        if [[ "$REF" != "$REF_NAME" -a "$REF" != "$REF_FULL_NAME" ]]; then
-          echo "::notice::$REF_NAME is $REF_FULL_NAME"
+          REF_NAME=$(git name-rev --name-only "$REF")
+          # if [[ -z "$REF_NAME" ]]
+          # then
+          #   GIT_MAX_DEPTH=2147483647 # 0x7fffffff
+          #   git fetch --depth=$GIT_MAX_DEPTH origin "$REF_NAME"
+          #   REF_NAME=$(git name-rev --name-only "$REF")
+          # fi
+
+          if [[ "$REF" != "$REF_NAME" ]]
+          then
+            echo "::notice::$REF is $REF_NAME"
+          fi
+
+          REF_FULL_NAME=$(git rev-parse --symbolic-full-name "$REF_NAME")
+        else
+          REF_FULL_NAME=$(git show-ref "$REF" | cut -d ' ' -f 2)
+
+          SHA=$(git rev-parse --short "$REF_FULL_NAME")
         fi
 
-        REF_TYPE=$(echo "$REF_FULL_NAME" | cut -d '/' -f 2)
-        echo "ref-type=$REF_TYPE" >> $GITHUB_OUTPUT
-        echo "::notice::Type is $REF_TYPE"
-
-        SHA=$(git rev-parse --short "$REF_FULL_NAME")
         echo "sha=$SHA" >> $GITHUB_OUTPUT
-        if [[ "$REF" != "$SHA" ]]; then
+        echo "ref-full-name=$REF_FULL_NAME" >> $GITHUB_OUTPUT
+
+        if ! (SHORT_SHA_LENGTH=$(git config --get core.abbrev))
+        then
+          SHORT_SHA_LENGTH=7
+        fi
+        echo "::notice::git config core.abbrev is $SHORT_SHA_LENGTH"
+
+        if [[ "$REF" != "$SHA" && "${REF:0:$SHORT_SHA_LENGTH}" != "$SHA" ]]
+        then
           echo "::notice::$REF is $SHA"
-        if
+        fi
+
+        if [[ "$REF" != "$REF_FULL_NAME" ]]
+        then
+          echo "::notice::$REF is $REF_FULL_NAME"
+        fi
 
     - name: Watch checks
       id: watch-checks
       shell: bash
       env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GH_TOKEN: ${{ inputs.github-token }}
         REPO: ${{ github.repository }}
-        SHA: ${{ get-git-ref-metadata.outputs.sha }}
-        TIMEOUT: ${{ timeout }}
+        JOB_IDS: ${{ steps.get-current-workflow-run.outputs.job-ids }}
+        SHA: ${{ steps.get-git-ref-metadata.outputs.sha }}
+        TIMEOUT: ${{ inputs.timeout }}
         CHECKS_WATCH_INTERVAL: ${{ inputs.checks-watch-interval }}
       run: |
+        echo "::group::Checks"
         CHECK_RUNS=$(gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "/repos/$REPO/commits/$SHA/check-runs" \
           --jq '[.check_runs.[] | pick (.id, .external_id, .name, .html_url, .status, .conclusion)]')
 
-        INCOMPLETE_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.status != "complete")]')
+        EXTERNAL_IDS=$(echo "$CHECK_RUNS" |
+          jq -c --argjson job_ids "$JOB_IDS" \
+          '[.[] | select(.id | [.] | inside($job_ids)) | .external_id ]')
+        EXTERNAL_ID_LIST=$(echo "$EXTERNAL_IDS" | jq -r '.[]' | tr '\n' ',' | sed -E 's/,/, /g; s/, $/\n/g')
+        echo "::notice::External ids associated with any job in the workflow run are $EXTERNAL_ID_LIST"
+        echo "$EXTERNAL_IDS" | jq '.'
+
+        RELEVANT_CHECKS=$(echo "$CHECK_RUNS" |
+          jq \
+          --argjson job_ids "$JOB_IDS" \
+          --argjson external_ids "$EXTERNAL_IDS" \
+          '[.[] | select(.id | [.] | inside($job_ids) | not) | select(.external_id | [.] | inside($external_ids) | not)]')
+
+        INCOMPLETE_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.status != "completed")]')
         INCOMPLETE_CHECK_COUNT=$(echo "$INCOMPLETE_CHECKS" | jq '. | length')
-        FAILED_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion != "success" and .conclusion != "skipped" and .conclusion != "neutral")]')
+
+        FAILED_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.status == "completed" and (.conclusion == null or (.conclusion != "success" and .conclusion != "skipped" and .conclusion != "neutral")))]')
         FAILED_CHECK_COUNT=$(echo "$FAILED_CHECKS" | jq '. | length')
+
+        CHECK_RUNS_TEXT=$(echo "$CHECK_RUNS" | jq -r \
+          --argjson job_ids "$JOB_IDS" \
+          --argjson external_ids "$EXTERNAL_IDS" \
+          '.[] | 
+          .name + "\n" + 
+          "  Id: " + (.id | tostring) + " (" + .html_url + ")\n" + 
+          "  Status: " + .status + "\n" + 
+          "  Conclusion: " + .conclusion + "\n" + 
+          (if .id | [.] | inside($job_ids) then "  This check is a job in the current Workflow.\n" elif .external_id | [.] | inside($external_ids) then "  This check is a job in another instance of the same Workflow.\n" else "" end)')
+        echo "$CHECK_RUNS_TEXT"
+        echo "::endgroup::"
 
         while [[ $INCOMPLETE_CHECK_COUNT -gt 0 && $FAILED_CHECK_COUNT -eq 0 ]]
         do
-          echo "::group::Number of pending checks: $INCOMPLETE_CHECK_COUNT"
           sleep $CHECKS_WATCH_INTERVAL
 
+          echo "::group::Checks"
           CHECK_RUNS=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "/repos/$REPO/commits/$SHA/check-runs" \
             --jq '[.check_runs.[] | pick (.id, .external_id, .name, .html_url, .status, .conclusion)]')
+          echo "::notice::$CHECK_RUNS"
 
-          INCOMPLETE_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.status != "complete")]')
+          EXTERNAL_IDS=$(echo "$CHECK_RUNS" |
+            jq -c --argjson job_ids "$JOB_IDS" \
+            '[.[] | select(.id | [.] | inside($job_ids)) | .external_id ]')
+          EXTERNAL_ID_LIST=$(echo "$EXTERNAL_IDS" | jq -r '.[]' | tr '\n' ',' | sed -E 's/,/, /g; s/, $/\n/g')
+          echo "::notice::External ids associated with any job in the workflow run are $EXTERNAL_ID_LIST"
+          echo "$EXTERNAL_IDS" | jq '.'
+
+          RELEVANT_CHECKS=$(echo "$CHECK_RUNS" |
+            jq \
+            --argjson job_ids "$JOB_IDS" \
+            --argjson external_ids "$EXTERNAL_IDS" \
+            '[.[] | select(.id | [.] | inside($job_ids) | not) | select(.external_id | [.] | inside($external_ids) | not)]')
+
+          INCOMPLETE_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.status != "completed")]')
           INCOMPLETE_CHECK_COUNT=$(echo "$INCOMPLETE_CHECKS" | jq '. | length')
-          FAILED_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion != "success" and .conclusion != "skipped" and .conclusion != "neutral")]')
+
+          FAILED_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.status == "completed" and (.conclusion == null or (.conclusion != "success" and .conclusion != "skipped" and .conclusion != "neutral")))]')
           FAILED_CHECK_COUNT=$(echo "$FAILED_CHECKS" | jq '. | length')
+
+          CHECK_RUNS_TEXT=$(echo "$CHECK_RUNS" | jq -r \
+            --argjson job_ids "$JOB_IDS" \
+            --argjson external_ids "$EXTERNAL_IDS" \
+            '.[] | 
+            .name + "\n" + 
+            "  Id: " + (.id | tostring) + " (" + .html_url + ")\n" + 
+            "  Status: " + .status + "\n" + 
+            "  Conclusion: " + .conclusion + "\n" + 
+            (if .id | [.] | inside($job_ids) then "  This check is a job in the current Workflow.\n" elif .external_id | [.] | inside($external_ids) then "  This check is a job in another instance of the same Workflow.\n" else "" end)')
+          echo "$CHECK_RUNS_TEXT"
           echo "::endgroup::"
         done
 
@@ -140,19 +214,32 @@ runs:
         if [[ $FAILED_CHECK_COUNT -gt 0 ]]
         then
           echo "conclusion=failure" >> $GITHUB_OUTPUT
-          echo "::error::Failed checks: $FAILED_CHECKS"
-          echo "::warning::Pending checks: $INCOMPLETE_CHECKS"
+
+          FAILED_CHECK_LIST=$(echo $FAILED_CHECKS | jq -r '.[] | .name' | tr '\n' '\t' | sed -E 's/\t/, /g; s/, $/\n/g')
+          echo "::error::Failed checks: $FAILED_CHECK_LIST"
+
+          if [[ $INCOMPLETE_CHECK_COUNT -gt 0 ]]
+          then
+            INCOMPLETE_CHECK_LIST=$(echo $INCOMPLETE_CHECKS | jq -r '.[] | .name' | tr '\n' '\t' | sed -E 's/\t/, /g; s/, $/\n/g')
+            echo "::warning::Pending checks: $INCOMPLETE_CHECK_LIST"
+          fi
           exit 1
         else
           echo "conclusion=success" >> $GITHUB_OUTPUT
-          SUCCESS_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion == "success")]')
-          echo "::info::Success checks: $SUCCESS_CHECKS"
-          SKIPPED_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion == "skipped")]')
-          echo "::info::Skipped checks: $SKIPPED_CHECKS"
-          NEUTRAL_CHECKS=$(echo "$CHECK_RUNS" | jq '[.[] | select(.conclusion == "neutral")]')
-          echo "::info::Neutral checks: $NEUTRAL_CHECKS"
+
+          SUCCESS_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.conclusion == "success")]')
+          SUCCESS_CHECK_LIST=$(echo $SUCCESS_CHECKS | jq -r '.[] | .name' | tr '\n' '\t' | sed -E 's/\t/, /g; s/, $/\n/g')
+          echo "::notice::Success checks: $SUCCESS_CHECK_LIST"
+
+          SKIPPED_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.conclusion == "skipped")]')
+          SKIPPED_CHECK_LIST=$(echo $SKIPPED_CHECKS | jq -r '.[] | .name' | tr '\n' '\t' | sed -E 's/\t/, /g; s/, $/\n/g')
+          echo "::notice::Skipped checks: $SKIPPED_CHECK_LIST"
+
+          NEUTRAL_CHECKS=$(echo "$RELEVANT_CHECKS" | jq '[.[] | select(.conclusion == "neutral")]')
+          NEUTRAL_CHECK_LIST=$(echo $NEUTRAL_CHECKS | jq -r '.[] | .name' | tr '\n' '\t' | sed -E 's/\t/, /g; s/, $/\n/g')
+          echo "::notice::Neutral checks: $NEUTRAL_CHECK_LIST"
         fi
 
 branding:
-  icon: 'box'
+  icon: 'clock'
   color: 'yellow'
